name: Docker PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  
  phpunit-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Composer Cache
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json', '**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Build Docker Image
        run: |
          docker build --no-cache -t starwars .

      - uses: php-actions/phpunit@v2
        with:
          php_version: '7.4'
          working-directory: ./tests
  