name: Docker PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build --no-cache -t starwars .

      - name: Run PHPUnit Tests in Docker
        run: |
          docker run --rm starwars vendor/bin/phpunit --configuration phpunit.xml
