name: Docker PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Composer Cache
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json', '**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Build Docker Image
        run: |
          docker build --no-cache -t starwars .

      - name: Install Composer Dependencies (including dev dependencies)
        run: |
          docker run --rm starwars:latest bash -c "cd /var/www/html && composer install --no-interaction --optimize-autoloader"

      - name: Run PHPUnit Tests
        run: |
          docker run --rm starwars:latest bash -c "cd /var/www/html && vendor/bin/phpunit"
